{
  LogResolution.m
  Filtration.m
  IntegralClosure.m
  Jacobian.m
  LocalPolynomialRing.m
  Misc.m
  Morphisms.m
  MultiplierIdeals.m
  NewtonPolygon.m
  PosChar.m
  ProximityMatrix.m
  PuiseuxExpansion.m
  SemiGroup.m
  Bernstein-Sato.m
}
