175,0
S,SquarefreePart,"Return the squarefree part of f, which is the largest (normalized) divisor g of f which is squarefree",0,1,0,0,0,0,0,0,0,469,,469,-38,-38,-38,-38,-38
S,SquarefreeFactorization,Factorize into squarefree polynomials the polynomial f,0,1,0,0,0,0,0,0,0,469,,82,-38,-38,-38,-38,-38
S,JacobianMatrix,"Returns the matrix with (i,j)'th entry the partial derivative of the i'th polynomial in the list with the j'th indeterminate of its parent ring",1,0,1,82,0,469,1,0,0,0,0,0,0,0,82,,178,-38,-38,-38,-38,-38
S,JacobianIdeal,Returns the ideal generated by all first partial derivatives of the polynomial,0,1,0,0,0,0,0,0,0,469,,470,-38,-38,-38,-38,-38
S,Polynomial,"The multivariate polynomial whose coefficients are C and monomials are M (so that Polynomial(Coefficients(f), Monomials(f))) equals f",2,0,1,82,0,-45,1,1,82,0,469,2,0,0,0,0,0,0,0,82,,0,0,82,,469,-38,-38,-38,-38,-38
